package ominext.com.expandableandloadmorerecyclerview.util;

/**
 * Created by LuongHH on 3/16/2017.
 */

public class Utils {

    public static final String LIST_FRIEND = "{\"error\":0,\"message\":\"Successfully !\",\"data\":{\"count\":5,\"list_friends\":[{\"id\":12,\"name\":\"haovt2\",\"nickname\":\"\",\"avatar\":\"http:\\/\\/echochat.ominext.co\\/images\\/default_user.png\",\"room_id\":\"35fb3830fa0b06404353aee04a9fbc97\",\"total_unread\":0,\"last_message\":\"hcjcjvjvjvkbjvjvjbjbjvjvjjvjvjvjvbjjbjbkvbjb dantri.com jvivibkbkbkbkvkbkbkbkbbkbkbkbkbk vnexpress.net jgjgk(+(+(+(+(+(+(\",\"show_time\":\"2017\\/01\\/20 08:42\"},{\"id\":17,\"name\":\"call2\",\"nickname\":\"\",\"avatar\":\"http:\\/\\/echochat.ominext.co\\/images\\/default_user.png\",\"room_id\":\"63168ef4d5677f599e85d1f3f0751ee1\",\"total_unread\":0,\"last_message\":\"A new album was created.\",\"show_time\":\"2017\\/01\\/20 08:29\"},{\"id\":10,\"name\":\"haovt\",\"nickname\":\"\",\"avatar\":\"http:\\/\\/echochat.ominext.co\\/images\\/default_user.png\",\"room_id\":\"0d61b48e3cfdbd2437a9598392913300\",\"total_unread\":0,\"last_message\":\"A new album was created.\",\"show_time\":\"2017\\/01\\/20 08:00\"},{\"id\":16,\"name\":\"call1\",\"nickname\":\"\",\"avatar\":\"http:\\/\\/echochat.ominext.co\\/images\\/default_user.png\",\"room_id\":\"7fafe075155a548b6e02c6099ce46871\",\"total_unread\":0,\"last_message\":\"\",\"show_time\":\"2017\\/01\\/17 07:29\"},{\"id\":15,\"name\":\"test1\",\"nickname\":\"\",\"avatar\":\"http:\\/\\/echochat.ominext.co\\/images\\/default_user.png\",\"room_id\":\"ebe6ee32bd3ac303c3a099c36580f1fc\",\"total_unread\":0,\"last_message\":\"jdjdjd\",\"show_time\":\"2017\\/01\\/16 11:04\"}],\"order\":\"5\"},\"detail\":{\"title\":\"Success\",\"message\":\"Successfully !\"}}";
    public static final String LIST_ROOM = "{\"error\":0,\"message\":\"Successfully !\",\"data\":{\"count\":2,\"list_rooms\":[{\"id\":2,\"name\":\"abc test\",\"avatar\":\"http:\\/\\/echochat.ominext.co\\/images\\/room\\/avatar\\/default_room.png\",\"total_unread\":2,\"is_creator\":0,\"last_message\":\"A note was created.\",\"show_time\":\"2017\\/01\\/20 08:54\"},{\"id\":1,\"name\":\"anv\",\"avatar\":\"http:\\/\\/echochat.ominext.co\\/images\\/room\\/avatar\\/default_room.png\",\"total_unread\":0,\"is_creator\":1,\"last_message\":\"\",\"show_time\":\"2017\\/01\\/12 15:57\"}],\"order\":\"1\"},\"detail\":{\"title\":\"Success\",\"message\":\"Successfully !\"}}";
}
